# Generated by Django 5.0.2 on 2024-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distribute',
            new_name='Distriute',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='buy_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
