# Generated by Django 5.0.2 on 2024-03-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0003_employee_company_alter_asset_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distriute',
            new_name='Distribute',
        ),
    ]
