# Generated by Django 5.0.2 on 2024-03-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0006_alter_distribute_asset_alter_distribute_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribute',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
